// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokerTournament.Infrastructure.Data;

#nullable disable

namespace PokerTournament.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407213249_AddTournamentBlindLevels")]
    partial class AddTournamentBlindLevels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PokerTournament.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("ChangedFields")
                        .HasColumnType("jsonb")
                        .HasColumnName("changed_fields");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<Guid?>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_logs_created_at");

                    b.HasIndex("TournamentId")
                        .HasDatabaseName("ix_audit_logs_tournament_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.BlindLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ante")
                        .HasColumnType("integer")
                        .HasColumnName("ante");

                    b.Property<int>("BigBlind")
                        .HasColumnType("integer")
                        .HasColumnName("big_blind");

                    b.Property<int>("BigBlindAnte")
                        .HasColumnType("integer")
                        .HasColumnName("big_blind_ante");

                    b.Property<Guid>("BlindStructureId")
                        .HasColumnType("uuid")
                        .HasColumnName("blind_structure_id");

                    b.Property<string>("BreakDescription")
                        .HasColumnType("text")
                        .HasColumnName("break_description");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsBreak")
                        .HasColumnType("boolean")
                        .HasColumnName("is_break");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("integer")
                        .HasColumnName("level_number");

                    b.Property<int>("SmallBlind")
                        .HasColumnType("integer")
                        .HasColumnName("small_blind");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("BlindStructureId", "LevelNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_blind_levels_structure_level");

                    b.ToTable("blind_levels", (string)null);
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.BlindStructure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DefaultAddon")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("default_addon");

                    b.Property<bool>("DefaultAddonAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("default_addon_allowed");

                    b.Property<bool>("DefaultAddonDoubleAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("default_addon_double_allowed");

                    b.Property<int?>("DefaultAddonStack")
                        .HasColumnType("integer")
                        .HasColumnName("default_addon_stack");

                    b.Property<decimal?>("DefaultBuyIn")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("default_buy_in");

                    b.Property<int?>("DefaultLateRegistrationLevel")
                        .HasColumnType("integer")
                        .HasColumnName("default_late_registration_level");

                    b.Property<int?>("DefaultMaxRebuys")
                        .HasColumnType("integer")
                        .HasColumnName("default_max_rebuys");

                    b.Property<decimal?>("DefaultRebuy")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("default_rebuy");

                    b.Property<int?>("DefaultRebuyStack")
                        .HasColumnType("integer")
                        .HasColumnName("default_rebuy_stack");

                    b.Property<int?>("DefaultRebuyUntilLevel")
                        .HasColumnType("integer")
                        .HasColumnName("default_rebuy_until_level");

                    b.Property<int?>("DefaultSeatsPerTable")
                        .HasColumnType("integer")
                        .HasColumnName("default_seats_per_table");

                    b.Property<int?>("DefaultStartingStack")
                        .HasColumnType("integer")
                        .HasColumnName("default_starting_stack");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("HomeGameId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_game_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("HomeGameId")
                        .HasDatabaseName("ix_blind_structures_home_game_id");

                    b.ToTable("blind_structures", (string)null);
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.CostExtra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Beneficiary")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("beneficiary");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsCashBox")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cash_box");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("paid_amount");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_status");

                    b.Property<string>("PixKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pix_key");

                    b.Property<string>("PixKeyType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pix_key_type");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId")
                        .IsUnique()
                        .HasDatabaseName("ix_cost_extras_tournament_id")
                        .HasFilter("is_cash_box = true");

                    b.ToTable("cost_extras", (string)null);
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.Elimination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("BlindLevel")
                        .HasColumnType("integer")
                        .HasColumnName("blind_level");

                    b.Property<bool>("Corrected")
                        .HasColumnType("boolean")
                        .HasColumnName("corrected");

                    b.Property<DateTimeOffset?>("CorrectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("corrected_at");

                    b.Property<Guid?>("CorrectedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("corrected_by");

                    b.Property<string>("CorrectionReason")
                        .HasColumnType("text")
                        .HasColumnName("correction_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("EliminatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eliminated_at");

                    b.Property<Guid?>("EliminatedByEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("eliminated_by_entry_id");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid?>("TableId")
                        .HasColumnType("uuid")
                        .HasColumnName("table_id");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EliminatedByEntryId");

                    b.HasIndex("EntryId")
                        .HasDatabaseName("ix_eliminations_entry_id");

                    b.HasIndex("TableId");

                    b.HasIndex("TournamentId")
                        .HasDatabaseName("ix_eliminations_tournament_id");

                    b.ToTable("eliminations", (string)null);
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.HomeGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DefaultAddon")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("default_addon");

                    b.Property<decimal?>("DefaultBuyIn")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("default_buy_in");

                    b.Property<decimal?>("DefaultRebuy")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("default_rebuy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("PixBeneficiary")
                        .HasColumnType("text")
                        .HasColumnName("pix_beneficiary");

                    b.Property<string>("PixKey")
                        .HasColumnType("text")
                        .HasColumnName("pix_key");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("America/Sao_Paulo")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_home_games_not_deleted")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_home_games_name")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("OwnerId");

                    b.ToTable("home_games", (string)null);
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.HomeGameMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HomeGameId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_game_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("UserId");

                    b.HasIndex("HomeGameId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_home_game_members_home_game_user");

                    b.ToTable("home_game_members", (string)null);
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TemplateKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template_key");

                    b.Property<Guid?>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_notification_logs_person_id");

                    b.HasIndex("TournamentId")
                        .HasDatabaseName("ix_notification_logs_tournament_id");

                    b.ToTable("notification_logs", (string)null);
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Document")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<Guid>("HomeGameId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_game_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nickname");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Jogador")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Whatsapp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("whatsapp");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_persons_not_deleted")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("HomeGameId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_persons_home_game_email")
                        .HasFilter("email IS NOT NULL AND deleted_at IS NULL");

                    b.HasIndex("HomeGameId", "Type")
                        .HasDatabaseName("ix_persons_home_game_type");

                    b.HasIndex("HomeGameId", "Whatsapp")
                        .IsUnique()
                        .HasDatabaseName("ix_persons_home_game_whatsapp")
                        .HasFilter("whatsapp IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.Ranking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AccumulatedPrize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("accumulated_prize");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid>("HomeGameId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_game_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ScoringFormula")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("scoring_formula");

                    b.Property<string>("ScoringMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Formula")
                        .HasColumnName("scoring_mode");

                    b.Property<Guid?>("ScoringRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("scoring_rule_id");

                    b.Property<string>("ScoringTable")
                        .HasColumnType("text")
                        .HasColumnName("scoring_table");

                    b.Property<string>("Season")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("season");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_rankings_not_deleted")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("HomeGameId")
                        .HasDatabaseName("ix_rankings_home_game_id");

                    b.HasIndex("ScoringRuleId");

                    b.ToTable("rankings", (string)null);
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.RankingScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BonusPoints")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("bonus_points");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("integer")
                        .HasColumnName("player_count");

                    b.Property<decimal>("Points")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("points");

                    b.Property<int?>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("RankingId")
                        .HasColumnType("uuid")
                        .HasColumnName("ranking_id");

                    b.Property<decimal>("TotalPoints")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_points");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("PersonId");

                    b.HasIndex("TournamentId");

                    b.HasIndex("RankingId", "PersonId", "TournamentId")
                        .IsUnique()
                        .HasDatabaseName("ix_ranking_scores_ranking_person_tournament");

                    b.ToTable("ranking_scores", (string)null);
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.ScoringRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("HomeGameId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_game_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PointsConfig")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("points_config");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("HomeGameId")
                        .HasDatabaseName("ix_scoring_rules_home_game_id");

                    b.ToTable("scoring_rules", (string)null);
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AddonAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("addon_allowed");

                    b.Property<decimal?>("AddonAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("addon_amount");

                    b.Property<bool>("AddonDoubleAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("addon_double_allowed");

                    b.Property<int?>("AddonStack")
                        .HasColumnType("integer")
                        .HasColumnName("addon_stack");

                    b.Property<Guid?>("BlindStructureId")
                        .HasColumnType("uuid")
                        .HasColumnName("blind_structure_id");

                    b.Property<decimal>("BuyInAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("buy_in_amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int?>("CurrentLevel")
                        .HasColumnType("integer")
                        .HasColumnName("current_level");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("HomeGameId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_game_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsTimerRunning")
                        .HasColumnType("boolean")
                        .HasColumnName("is_timer_running");

                    b.Property<int?>("LateRegistrationLevel")
                        .HasColumnType("integer")
                        .HasColumnName("late_registration_level");

                    b.Property<int?>("MaxRebuys")
                        .HasColumnType("integer")
                        .HasColumnName("max_rebuys");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("NetPrizePool")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("net_prize_pool");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("PlayersRemaining")
                        .HasColumnType("integer")
                        .HasColumnName("players_remaining");

                    b.Property<bool>("PrizeConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("prize_confirmed");

                    b.Property<DateTimeOffset?>("PrizeConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prize_confirmed_at");

                    b.Property<Guid?>("RankingId")
                        .HasColumnType("uuid")
                        .HasColumnName("ranking_id");

                    b.Property<decimal?>("RebuyAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("rebuy_amount");

                    b.Property<int?>("RebuyStack")
                        .HasColumnType("integer")
                        .HasColumnName("rebuy_stack");

                    b.Property<int?>("RebuyUntilLevel")
                        .HasColumnType("integer")
                        .HasColumnName("rebuy_until_level");

                    b.Property<int>("SeatsPerTable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(9)
                        .HasColumnName("seats_per_table");

                    b.Property<bool>("SettlementClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("settlement_closed");

                    b.Property<DateTimeOffset?>("SettlementClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settlement_closed_at");

                    b.Property<Guid?>("SettlementClosedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("settlement_closed_by");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.Property<int>("StartingStack")
                        .HasColumnType("integer")
                        .HasColumnName("starting_stack");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("TimerElapsedSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timer_elapsed_seconds");

                    b.Property<DateTimeOffset?>("TimerPausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timer_paused_at");

                    b.Property<DateTimeOffset?>("TimerStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timer_started_at");

                    b.Property<int>("TotalAddons")
                        .HasColumnType("integer")
                        .HasColumnName("total_addons");

                    b.Property<decimal>("TotalCosts")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_costs");

                    b.Property<int>("TotalEntries")
                        .HasColumnType("integer")
                        .HasColumnName("total_entries");

                    b.Property<decimal>("TotalPrizePool")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_prize_pool");

                    b.Property<int>("TotalRebuys")
                        .HasColumnType("integer")
                        .HasColumnName("total_rebuys");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("BlindStructureId");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_tournaments_date");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_tournaments_not_deleted")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("HomeGameId")
                        .HasDatabaseName("ix_tournaments_home_game_id");

                    b.HasIndex("RankingId")
                        .HasDatabaseName("ix_tournaments_ranking_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_tournaments_status");

                    b.ToTable("tournaments", null, t =>
                        {
                            t.HasCheckConstraint("ck_tournaments_status", "status IN ('Draft','OpenForRegistration','InProgress','BreakSettlement','Finished','Cancelled')");
                        });
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.TournamentBlindLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ante")
                        .HasColumnType("integer")
                        .HasColumnName("ante");

                    b.Property<int>("BigBlind")
                        .HasColumnType("integer")
                        .HasColumnName("big_blind");

                    b.Property<int>("BigBlindAnte")
                        .HasColumnType("integer")
                        .HasColumnName("big_blind_ante");

                    b.Property<string>("BreakDescription")
                        .HasColumnType("text")
                        .HasColumnName("break_description");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsBreak")
                        .HasColumnType("boolean")
                        .HasColumnName("is_break");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("integer")
                        .HasColumnName("level_number");

                    b.Property<int>("SmallBlind")
                        .HasColumnType("integer")
                        .HasColumnName("small_blind");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "LevelNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_tournament_blind_levels_tournament_level");

                    b.ToTable("tournament_blind_levels", (string)null);
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.TournamentDealer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("TournamentId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_tournament_dealers_tournament_person");

                    b.ToTable("tournament_dealers", (string)null);
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.TournamentEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AddonAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("addon_amount");

                    b.Property<bool>("AddonDouble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("addon_double");

                    b.Property<bool>("AddonPurchased")
                        .HasColumnType("boolean")
                        .HasColumnName("addon_purchased");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("balance");

                    b.Property<decimal>("BuyInAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("buy_in_amount");

                    b.Property<bool>("BuyInPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("buy_in_paid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EliminatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eliminated_at");

                    b.Property<Guid?>("EliminatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("eliminated_by_id");

                    b.Property<Guid?>("EliminationTableId")
                        .HasColumnType("uuid")
                        .HasColumnName("elimination_table_id");

                    b.Property<int>("EntryNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("entry_number");

                    b.Property<int?>("FinalPosition")
                        .HasColumnType("integer")
                        .HasColumnName("final_position");

                    b.Property<bool>("IsReentry")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reentry");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OriginalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_entry_id");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_status");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<decimal?>("PrizeAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("prize_amount");

                    b.Property<bool>("PrizePaid")
                        .HasColumnType("boolean")
                        .HasColumnName("prize_paid");

                    b.Property<decimal?>("RankingPoints")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("ranking_points");

                    b.Property<int>("RebuyCount")
                        .HasColumnType("integer")
                        .HasColumnName("rebuy_count");

                    b.Property<decimal>("RebuyTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("rebuy_total");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<Guid?>("RegisteredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("registered_by");

                    b.Property<int?>("SeatNumber")
                        .HasColumnType("integer")
                        .HasColumnName("seat_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TableId")
                        .HasColumnType("uuid")
                        .HasColumnName("table_id");

                    b.Property<decimal>("TotalDue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_due");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_paid");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EliminatedById");

                    b.HasIndex("FinalPosition")
                        .HasDatabaseName("ix_tournament_entries_position");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_tournament_entries_person_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_tournament_entries_status");

                    b.HasIndex("TableId")
                        .HasDatabaseName("ix_tournament_entries_table_id");

                    b.HasIndex("TournamentId")
                        .HasDatabaseName("ix_tournament_entries_tournament_id");

                    b.HasIndex("TournamentId", "PersonId", "EntryNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_tournament_entries_tournament_person_entry");

                    b.ToTable("tournament_entries", (string)null);
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.TournamentPrize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<bool>("Paid")
                        .HasColumnType("boolean")
                        .HasColumnName("paid");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("percentage");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("TournamentId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_tournament_prizes_tournament_position");

                    b.ToTable("tournament_prizes", (string)null);
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.TournamentTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DealerPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealer_person_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFinalTable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_final_table");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("integer")
                        .HasColumnName("max_seats");

                    b.Property<string>("TableName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("table_name");

                    b.Property<int>("TableNumber")
                        .HasColumnType("integer")
                        .HasColumnName("table_number");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DealerPersonId");

                    b.HasIndex("TournamentId", "TableNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_tournament_tables_tournament_number");

                    b.ToTable("tournament_tables", (string)null);
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<decimal?>("CashAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cash_amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<decimal?>("PixAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("pix_amount");

                    b.Property<Guid?>("PixDestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("pix_destination_id");

                    b.Property<string>("ReversalReason")
                        .HasColumnType("text")
                        .HasColumnName("reversal_reason");

                    b.Property<DateTimeOffset?>("ReversedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reversed_at");

                    b.Property<Guid?>("ReversedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reversed_by");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EntryId")
                        .HasDatabaseName("ix_transactions_entry_id");

                    b.HasIndex("PixDestinationId");

                    b.HasIndex("TournamentId")
                        .HasDatabaseName("ix_transactions_tournament_id");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nickname");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Whatsapp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("whatsapp");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.BlindLevel", b =>
                {
                    b.HasOne("PokerTournament.Domain.Entities.BlindStructure", "BlindStructure")
                        .WithMany("Levels")
                        .HasForeignKey("BlindStructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlindStructure");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.BlindStructure", b =>
                {
                    b.HasOne("PokerTournament.Domain.Entities.HomeGame", "HomeGame")
                        .WithMany()
                        .HasForeignKey("HomeGameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HomeGame");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.CostExtra", b =>
                {
                    b.HasOne("PokerTournament.Domain.Entities.Tournament", "Tournament")
                        .WithMany("CostExtras")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.Elimination", b =>
                {
                    b.HasOne("PokerTournament.Domain.Entities.TournamentEntry", "EliminatedByEntry")
                        .WithMany()
                        .HasForeignKey("EliminatedByEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokerTournament.Domain.Entities.TournamentEntry", "Entry")
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokerTournament.Domain.Entities.TournamentTable", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokerTournament.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Eliminations")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EliminatedByEntry");

                    b.Navigation("Entry");

                    b.Navigation("Table");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.HomeGame", b =>
                {
                    b.HasOne("PokerTournament.Domain.Entities.User", "Owner")
                        .WithMany("OwnedHomeGames")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.HomeGameMember", b =>
                {
                    b.HasOne("PokerTournament.Domain.Entities.HomeGame", "HomeGame")
                        .WithMany("Members")
                        .HasForeignKey("HomeGameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokerTournament.Domain.Entities.Person", "Person")
                        .WithMany("HomeGameMembers")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokerTournament.Domain.Entities.User", "User")
                        .WithMany("HomeGameMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HomeGame");

                    b.Navigation("Person");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.NotificationLog", b =>
                {
                    b.HasOne("PokerTournament.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokerTournament.Domain.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Person");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.Person", b =>
                {
                    b.HasOne("PokerTournament.Domain.Entities.HomeGame", "HomeGame")
                        .WithMany("Persons")
                        .HasForeignKey("HomeGameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HomeGame");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.Ranking", b =>
                {
                    b.HasOne("PokerTournament.Domain.Entities.HomeGame", "HomeGame")
                        .WithMany("Rankings")
                        .HasForeignKey("HomeGameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokerTournament.Domain.Entities.ScoringRule", "ScoringRule")
                        .WithMany()
                        .HasForeignKey("ScoringRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HomeGame");

                    b.Navigation("ScoringRule");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.RankingScore", b =>
                {
                    b.HasOne("PokerTournament.Domain.Entities.TournamentEntry", "Entry")
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokerTournament.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokerTournament.Domain.Entities.Ranking", "Ranking")
                        .WithMany("Scores")
                        .HasForeignKey("RankingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokerTournament.Domain.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Person");

                    b.Navigation("Ranking");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.ScoringRule", b =>
                {
                    b.HasOne("PokerTournament.Domain.Entities.HomeGame", "HomeGame")
                        .WithMany()
                        .HasForeignKey("HomeGameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HomeGame");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.Tournament", b =>
                {
                    b.HasOne("PokerTournament.Domain.Entities.BlindStructure", "BlindStructure")
                        .WithMany()
                        .HasForeignKey("BlindStructureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokerTournament.Domain.Entities.HomeGame", "HomeGame")
                        .WithMany("Tournaments")
                        .HasForeignKey("HomeGameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokerTournament.Domain.Entities.Ranking", "Ranking")
                        .WithMany("Tournaments")
                        .HasForeignKey("RankingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BlindStructure");

                    b.Navigation("HomeGame");

                    b.Navigation("Ranking");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.TournamentBlindLevel", b =>
                {
                    b.HasOne("PokerTournament.Domain.Entities.Tournament", "Tournament")
                        .WithMany("BlindLevels")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.TournamentDealer", b =>
                {
                    b.HasOne("PokerTournament.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokerTournament.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Dealers")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.TournamentEntry", b =>
                {
                    b.HasOne("PokerTournament.Domain.Entities.TournamentEntry", "EliminatedByEntry")
                        .WithMany()
                        .HasForeignKey("EliminatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokerTournament.Domain.Entities.Person", "Person")
                        .WithMany("TournamentEntries")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokerTournament.Domain.Entities.TournamentTable", "Table")
                        .WithMany("Entries")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokerTournament.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Entries")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EliminatedByEntry");

                    b.Navigation("Person");

                    b.Navigation("Table");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.TournamentPrize", b =>
                {
                    b.HasOne("PokerTournament.Domain.Entities.TournamentEntry", "Entry")
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokerTournament.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Prizes")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.TournamentTable", b =>
                {
                    b.HasOne("PokerTournament.Domain.Entities.Person", "DealerPerson")
                        .WithMany()
                        .HasForeignKey("DealerPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokerTournament.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Tables")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DealerPerson");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("PokerTournament.Domain.Entities.TournamentEntry", "Entry")
                        .WithMany("Transactions")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokerTournament.Domain.Entities.CostExtra", "PixDestination")
                        .WithMany()
                        .HasForeignKey("PixDestinationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokerTournament.Domain.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("PixDestination");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.BlindStructure", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.HomeGame", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Persons");

                    b.Navigation("Rankings");

                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.Person", b =>
                {
                    b.Navigation("HomeGameMembers");

                    b.Navigation("TournamentEntries");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.Ranking", b =>
                {
                    b.Navigation("Scores");

                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("BlindLevels");

                    b.Navigation("CostExtras");

                    b.Navigation("Dealers");

                    b.Navigation("Eliminations");

                    b.Navigation("Entries");

                    b.Navigation("Prizes");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.TournamentEntry", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.TournamentTable", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("PokerTournament.Domain.Entities.User", b =>
                {
                    b.Navigation("HomeGameMemberships");

                    b.Navigation("OwnedHomeGames");
                });
#pragma warning restore 612, 618
        }
    }
}
